### ISSUE TITLE
The website of LIP benchmark is unavailable

### ISSUE THREAD

**Issue by vicmax** [Engineering-Course/caffe_ssl#5]
It seems like your website [http://hcp.sysu.edu.cn/lip](http://hcp.sysu.edu.cn/lip) is unavailable for such a long time.

**Comment by Engineering-Course** [comment]
Sorry about that.
The new address is [here](http://www.sysu-hcp.net/lip/).
We have already changed it in the [LIP_SSL](https://github.com/Engineering-Course/LIP_SSL) repository.

**Comment by vicmax** [comment]
OK. Thanks~
